


export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_SINGLEUSER_SUCCESS="GET_SINGLEUSER_SUCCESS"
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_DELETE = "POST_USER_DELETE";


